version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        container_name: perekup-frontend
        restart: unless-stopped
        ports:
            - '80:80'
        environment:
            - NODE_ENV=production
        healthcheck:
            test: ['CMD', 'wget', '-q', '--spider', 'http://localhost']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
